<?php

namespace App\UI\User;

use App\UI\Control\BaseControl;
use Nette;

class UserGrid extends BaseControl
{

	public function createComponent(string $name): ?Nette\ComponentModel\IComponent
	{
		return parent::createComponent($name); // TODO: Change the autogenerated stub
	}
}
